sudo: false
language: java
jdk:
  - oraclejdk8
deploy:
  provider: script
  script: bash release-and-publish.sh
  on:
#    repo: neueda/jetbrains-plugin-graph-database-support
    branch: master
    tags: true
script:
  - ./gradlew clean test --stacktrace